### ISSUE TITLE
f3 init is not workin

### ISSUE THREAD

**Issue by guzz** [feathers-nuxt/template-app#1]
When I run `f3 init` it says `command not found`.

I´ve read the f3 documentation but couldnt find any reference for a global install. 

Do I have to make any other config for it to work?

I understand that this is a very early stage project, but I really liked your approach, if I can help in any way.

**Comment by kharhys** [comment]
You do need to install [f3](https://github.com/feathers-nuxt/cli) globally. It's basically a `cli` utility that uses the template in this repo to initialize your project among other tasks. You may use [sao](https://sao.js.org/) instead but I haven't tested that yet. However, under the hood, `f3` uses `sao` providing it the template in this repo. 

At the moment the package isn't published to `npm` so you'd install from [github](https://github.com/feathers-nuxt/cli) using 
>  `yarn add global github:feathers-nuxt/cli` or  `npm i -g github:feathers-nuxt/cli` 

Then invoke `f3` to see a list of available commands.  `f3 init test` will clone this repository into `test` directory and then invoke `yarn install` inside `test` directory. 

To  enjoy feathers-nuxt goodness, `cd test`. Invoke `yarn dev` to run app in development. Invoke `yarn run` to see a list of all available tasks in your project.

Documentation is scarce at this point but I'm working to have at least rough guides to get anyone quickly started. I'd actually appreciate help with documenting the project if you are interested in that. Thanks for your interest in the project.

**Comment by kharhys** [comment]
Closing this issue because comprehensive set up [documentation](https://feathers-nuxt.netlify.com/) is now available.
